# Autogenerated file
def render(delays):
    yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>CANBell - Sensor Delays</title>
    <link rel=\"stylesheet\" href=\"/static/pure-min.css\">
  </head>
  <body>
    <form class=\"pure-form pure-form-aligned\" action=\"/delays\" method=\"post\">
      <legend>Sensor Delays (ms)</legend>
      <fieldset>
        """
    for i in range(len(delays)):
        yield """          <div class=\"pure-control-group\">
            <label>Bell #"""
        yield str(i + 1)
        yield """</label>
            <input type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]"""
        yield """{1,3}\" required name=\"bell"""
        yield str(i)
        yield """\" value="""
        yield str(delays[i])
        yield """ />
          </div>
        """
    yield """        <div class=\"pure-controls\">
          <button name=\"action\" value=\"cancel\" type=\"submit\" class=\"pure-button pure-button-secondary\">Cancel</button>
          <button name=\"action\" value=\"submit\" type=\"submit\" class=\"pure-button pure-button-primary\">Set</button>
        </div>
      </fieldset>
    </form>
  </body>
</html>

"""
