# Autogenerated file
def render(dirs, logcounts, free):
    yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>CANBell</title>
    <link rel=\"stylesheet\" href=\"/static/pure-min.css\">
    <link rel=\"stylesheet\" href=\"/static/grids-responsive-min.css\">
    <link rel=\"stylesheet\" href=\"/static/style.css\">
  </head>
  <body>
    <div class=\"pure-menu pure-menu-horizontal\">
      <ul class=\"pure-menu-list\">
        <li class=\"pure-menu-item pure-menu-selected\">
          <a href=\"#\" class=\"pure-menu-link\">Logs</a>
        </li>
        <li class=\"pure-menu-item\">
          <a href=\"/delays\" class=\"pure-menu-link\">Delays</a>
        </li>
      </ul>
    </div>
    <hr>
    <div class=\"contents\">
      <form class=\"pure-form pure-form-aligned\" action=\"/download\">
          """
    for i in range(len(dirs)):
        yield """            <div class=\"pure-control-group\">
              <label class=\"pure-radio\">
                """
        yield str(dirs[i])
        yield """ ("""
        yield str(logcounts[i])
        yield """)
              </label>
              <input type=\"radio\" name=\"logRadios\">
            </div>
          """
    yield """          <div class=\"pure-controls\">
            <button name=\"action\" value=\"download\" type=\"submit\" class=\"pure-button pure-button-primary\">Download</button>
          </div>
      </form>
      <div class=\"free-info\">
        <p>"""
    yield str(free // 1000)
    yield """ kB free</p>
      </div>
    </div>
  </body>
</html>

"""
